---
title: "Untitled"
author: "Shuyi SHEN"
date: "11/15/2019"
output: github_document
---

```{r}
library(tidyverse)
library(broom)
library(modelr)
library(ggplot2)
```

# Problem 1
```{r}
birthweight = read.csv("birthweight.csv") %>%
        janitor::clean_names() %>%
  mutate(babysex = factor(babysex),
         frace   = factor(frace),
         malform = factor(malform),
         mrace   = factor(frace))
  

is.na(birthweight) %>% summary()
```

```{r}
fit = lm(bwt~.,data = birthweight)
anova(fit)

```


```{r}
fit_0 = lm(bwt~babysex+bhead+blength+delwt+fincome+frace+gaweeks+mheight+momage+mrace+parity+ppbmi+smoken,data = birthweight)

birthweight %>% 
add_residuals(fit_0) %>% 
add_predictions(fit_0) %>% 
  ggplot(aes(x=pred,y=resid))+geom_point()

```

## compare the model
```{r}
fit_1 = lm(bwt~blength+gaweeks,data=birthweight)
fit_2 = lm(bwt~bhead+blength+babysex, data=birthweight)

cv_df=crossv_mc(birthweight,100)

cv_df %>% pull(train) %>% .[[1]] %>% as_tibble
cv_df %>% pull(test) %>% .[[1]] %>% as_tibble

cv_df=
  cv_df %>% 
  mutate(
    train = map(train,as_tibble),
    test = map(test,as_tibble)
  )


cv_df = 
  cv_df %>% 
  mutate(mod_0  = map(train,
                      ~lm(bwt~babysex+bhead+blength+delwt+fincome+                                            frace+gaweeks+mheight+momage+mrace+parity+ppbmi+smoken,data=.x)),
         mod_1  = map(train, ~lm(bwt~blength+gaweeks,data=.x)),
         mod_2  = map(train, ~lm(bwt~bhead+blength+babysex, data=.x))) %>% 
  mutate(rmse_0 = map2_dbl(mod_0, test, ~rmse(model = .x, data = .y)),
         rmse_1 = map2_dbl(mod_1, test, ~rmse(model = .x, data = .y)),
         rmse_2 = map2_dbl(mod_2, test, ~rmse(model = .x, data = .y)))

cv_df %>% 
  select(starts_with("rmse")) %>% 
pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()

```

